version: "3.9"

services:
  reverse-proxy:
    image: traefik:2.6.3
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
      # - "8081:8080"
    volumes:
      - $PWD/config:/etc/traefik
      - $PWD/certificates:/certificates
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - reverse-proxy-network
    restart: always

networks:
  reverse-proxy-network:
    name: reverse-proxy-network
    driver: bridge
