global:
  checkNewVersion: true
  sendAnonymousUsage: false

# Entrypoints configuration
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

# TLS configuration
tls:
  certificates:
    - certFile: /certificates/STAR.example.com/STAR.example.com.pem
      keyFile: /certificates/STAR.example.com/STAR.example.com.key

# Providers configuration
providers:
  docker:
    # If set to false, containers that do not have a traefik.enable=true label are ignored from the resulting routing configuration
    exposedByDefault: false
    network: "reverse-proxy-network"
    watch: true
  
  file:
    directory: /etc/traefik
    watch: true

# API and dashboard configuration
api:
  insecure: true
